name: Main Workflow
run-name: Started by ${{github.actor}}, for push ${{github.event_name}}
on: [push]
jobs:
    run-tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ['3.10', '3.11']
                with-orjson: [True, False]
        steps:
            - name: Checkout Main
              uses: actions/checkout@main
            
            - name: Setup Pyhon
              uses: actions/setup-python@v3
              with:
                  python-version: ${{matrix.python-version}}
                  architecture: x64

            - name: Install requirments
              run: pip install -r requirements.txt
            
            - name: Installing Orjson
              if: ${{matrix.with-orjson}}
              run: pip install orjson
            
            - name: Run tests
              run: python -m unittest discover
                  