name: Main Workflow
run-name: Started by ${{github.actor}}, for push to ${{github.ref}}
on: [push]
jobs:
    run-tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ['3.10', '3.11']
                with-orjson: [True, False]
        steps:
            - name: Checkout Main
              uses: actions/checkout@main
            
            - name: Setup Pyhon
              uses: actions/setup-python@v3
              with:
                  python-version: ${{matrix.python-version}}
                  architecture: x64

            - name: Install requirments
              run: |
                pip install --upgrade pip
                pip install -r requirements.txt
            
            - name: Installing Orjson
              if: ${{matrix.with-orjson}}
              run: pip install orjson
            
            - name: Run tests
              run: |
              python test_minimal_paths.py
              python test_model.py

    run-coverage:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Main
              uses: actions/checkout@main
            
            - name: Setup Pyhon
              uses: actions/setup-python@v3
  
            - name: Install requirments
              run: |
                pip install --upgrade pip
                pip install -r requirements.txt
                pip install orjson
            
            - name: Run coverage
              run: coverage run -m unittest discover  